### Get users
GET http://localhost:8080/users

### Create a user
POST http://localhost:8080/users
Content-Type: application/json

{
  "Name": "Qinny",
  "Email": "muttaqin.muzakkir@gmail.com",
  "PasswordHash": "Muttaqin"
}
